2024-09-19 12:57:14,971 - telegram.ext.Application - INFO - Application started
2024-09-19 12:57:25,824 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, handle_text
2024-09-19 12:57:25,825 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, save_transaction
2024-09-19 12:59:22,866 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 12:59:22,868 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 12:59:55,091 - telegram.ext.Application - INFO - Application started
2024-09-19 12:59:58,783 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, handle_text
2024-09-19 12:59:58,784 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, save_transaction
2024-09-19 13:00:57,616 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 13:00:57,617 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 13:01:00,089 - telegram.ext.Application - INFO - Application started
2024-09-19 13:01:00,826 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
2024-09-19 13:01:52,135 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 13:01:52,136 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 13:01:55,032 - telegram.ext.Application - INFO - Application started
2024-09-19 13:01:56,344 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
2024-09-19 13:02:36,916 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 13:02:36,916 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 13:02:39,700 - telegram.ext.Application - INFO - Application started
2024-09-19 13:02:41,430 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
2024-09-19 13:02:41,439 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1335, in process_update
    await coroutine
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/core.py", line 399, in show_records
    records = get_records(user_id, command)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/file_ops.py", line 276, in get_records
    sum_per_cat = show_sum_per_cat(user_id, file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/pandas_ops.py", line 49, in show_sum_per_cat
    current_month_data = get_current_month_data(user_id, file_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/pandas_ops.py", line 42, in get_current_month_data
    current_month_data = recalculate_currency(current_month_data, currency,exchange_rates)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/pandas_ops.py", line 227, in recalculate_currency
    data['amount_cr_currency'] = calculate_new_value(data, user_currency, exchange_rates)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Documents/Documents - SkyNet_1/Programming/budgetbot/pandas_ops.py", line 201, in calculate_new_value
    print('currency is: \n', data['currency'][1])
                             ~~~~~~~~~~~~~~~~^^^
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/itsoneword/Downloads/DevVenv/DevVenv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 1
2024-09-19 13:02:53,145 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, handle_text
2024-09-19 13:02:53,147 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, save_transaction
2024-09-19 13:05:02,605 - telegram.ext.Application - INFO - Application started
2024-09-19 13:05:03,226 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
2024-09-19 13:10:38,578 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 13:10:38,581 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 13:10:41,324 - telegram.ext.Application - INFO - Application started
2024-09-19 13:10:43,751 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
2024-09-19 13:16:34,675 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-09-19 13:16:34,678 - telegram.ext.Application - INFO - Application.stop() complete
2024-09-19 13:16:37,314 - telegram.ext.Application - INFO - Application started
2024-09-19 13:16:39,434 - user_interactions - INFO - UserID: 46304833, Slava, DY0R2, show_records
